### ISSUE TITLE
Wrong behaviour of org-change-accept and reject

### ISSUE THREAD

**Issue by Jousimies** [drghirlanda/org-change#1]
In one org-file, I tried to use org-change-replace command, a region on text `foo`, changed to `[[change:foo][Bar]]`.

But If I use org-change-accept or org-change-reject, the text `[[change:foo][Bar]]` was deleted totally. Apparently it is wrong.

GNU Emacs 29.0.90 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3 (Build 22E252))

Org mode version 9.6.4 (release_9.6.4-9-g8eb209 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)

By the way, thank you for this awesome package, I like it.

**Comment by drghirlanda** [comment]
Thanks for this! There was a misplaced parentheses in the accept-or-reject code that caused the new text not to be inserted. I have pushed a fix.

**Comment by Jousimies** [comment]
Thanks.

Now, `org-change-accept` worked as respect, But `org-change-reject` will delete content, should it keep old text there instead of delete it?
