### ISSUE TITLE
org-change-replace

### ISSUE THREAD

**Issue by cornelis-fp** [drghirlanda/org-change#4]
“replace” duplicated the replaced text, tagging it on to the end of the [[change:old-text][new-text]]old-text – undesirable result; please rectify.

**Comment by drghirlanda** [comment]
Thanks! This is actually a new feature to show deleted/replaced text alongside new text instead of hiding it, see the "Showing deleted text" section in the README. However, I meant for it to be off by default, while it was on by mistake. I have fixed this in commit 3771272.
